name: vitaltrack
description: "Aplicación móvil interactiva para el monitoreo de la salud conectada a dispositivos IoT"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  
  # Estado
  provider: ^6.1.5
  
  # UI y Gráficos
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1
  
  # Backend
  supabase_flutter: ^2.6.0
  
  # Persistencia
  shared_preferences: ^2.3.4
  
  # Utilidades
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/